### ISSUE TITLE
Unexpected border size on Microsoft Edge

### ISSUE THREAD

**Issue by GeeLaw** [shifuchen/Key-Expediter#1]
![image](https://cloud.githubusercontent.com/assets/4462444/15973939/70fd5890-2f78-11e6-8dc8-88b7654a8445.png)

The input box seems to have wrong border size on Microsoft Edge. Windows 10 build 10586.

**Comment by shifuchen** [comment]
Unfortunately, this issue did not reappear in my Edge browser. However, I made an attempt to reconstruct the elements displayed. Kindly check if the things are well organized in your browser now.

**Comment by GeeLaw** [comment]
It's solved but it seems that every element gets the thin border haha.
